services:
  pd:
    build:
      context: ./service/pd
      args:
        - TIDB_VERSION=${TIDB_VERSION}
    command: "--config=/etc/tidb/pd.toml"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    ports:
      - "${BIND_ADDRESS}${BIND_COLON}${PD_CLIENT_PORT}:2379"
      - "${BIND_ADDRESS}${BIND_COLON}${PD_PEER_PORT}:2380"
    volumes:
      - ./service/pd/pd.toml:/etc/tidb/pd.toml
      - ${DATA_DIR}/pd:/data/pd

  tikv:
    build:
      context: ./service/tikv
      args:
        - TIDB_VERSION=${TIDB_VERSION}
    command: "--config=/etc/tidb/tikv.toml"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    ports:
      - "${BIND_ADDRESS}${BIND_COLON}${TIKV_SERVER_PORT}:20160"
      - "${BIND_ADDRESS}${BIND_COLON}${TIKV_STATUS_PORT}:20180"
    depends_on:
      - pd
    volumes:
      - ./service/tikv/tikv.toml:/etc/tidb/tikv.toml
      - ${DATA_DIR}/tikv:/data/tikv

  tidb:
    build:
      context: ./service/tidb
      args:
        - TIDB_VERSION=${TIDB_VERSION}
    command: "--config=/etc/tidb/tidb.toml"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    ports:
      - "${BIND_ADDRESS}${BIND_COLON}${TIDB_SERVER_PORT}:4000"
      - "${BIND_ADDRESS}${BIND_COLON}${TIDB_STATUS_PORT}:10080"
    depends_on:
      - tikv
      - pd
    volumes:
      - ./service/tidb/tidb.toml:/etc/tidb/tidb.toml
      - ${DATA_DIR}/tidb:/data/tidb
