services:
  pd:
    build:
      context: ./service/pd
      args:
        - TIDB_VERSION=${TIDB_VERSION}
    container_name: tidb_pd
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    ports:
      - "${BIND_ADDRESS}${BIND_COLON}${PD_CLIENT_PORT}:2379"
      - "${BIND_ADDRESS}${BIND_COLON}${PD_PEER_PORT}:2380"
    environment:
      - PD_SERVER_NAME=pd
      - INITIAL_CLUSTER=pd=http://pd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - ${DATA_DIR}/pd:/pd

  tikv:
    build:
      context: ./service/tikv
      args:
        - TIDB_VERSION=${TIDB_VERSION}
    container_name: tidb_tikv
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    ports:
      - "${BIND_ADDRESS}${BIND_COLON}${TIKV_SERVER_PORT}:20160"
      - "${BIND_ADDRESS}${BIND_COLON}${TIKV_STATUS_PORT}:20180"
    environment:
      - PD_ADDR=pd:2379
    depends_on:
      - pd
    volumes:
      - ${DATA_DIR}/tikv:/tikv

  tidb:
    build:
      context: ./service/tidb
      args:
        - TIDB_VERSION=${TIDB_VERSION}
    container_name: tidb_server
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    ports:
      - "${BIND_ADDRESS}${BIND_COLON}${TIDB_SERVER_PORT}:4000"
      - "${BIND_ADDRESS}${BIND_COLON}${TIDB_STATUS_PORT}:10080"
    environment:
      - PATH="bin:$PATH"
      - MYSQL_HOST=0.0.0.0
      - MYSQL_PORT=4000
      - STORE=tikv
      - PATH=bin:$PATH
      - PD_ADDR=pd:2379
    depends_on:
      - tikv
      - pd
    volumes:
      - ${DATA_DIR}/tidb:/tidb
