global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node
    static_configs:
      - targets: ["prometheus-node:9100"]
  - job_name: redis
    static_configs:
      - targets: ["prometheus-redis:9121"]
  - job_name: mysql
    static_configs:
      - targets: ["prometheus-mysql:9104"]
  - job_name: kafka
    static_configs:
      - targets: ["prometheus-kafka:9308"]
  - job_name: rabbitmq
    static_configs:
      - targets: ["rabbitmq:15692"]
  - job_name: clickhouse
    static_configs:
      - targets: ["clickhouse:9363"]
  - job_name: fs-project
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["192.168.0.146:7808"]
  - job_name: nvidia
    metrics_path: '/metrics'
    static_configs:
      - targets: ["172.16.0.233:9400"]
