# https://github.com/tikv/tikv/blob/release-8.5/etc/config-template.toml

[pd]
endpoints = ["pd:2379"]

[server]
addr = "0.0.0.0:20160"
advertise-addr = "tikv:20160"
status-addr = "0.0.0.0:20180"

[storage]
data-dir = "/data/tikv"
