filebeat.inputs:
- type: log
  paths:
    - /data/fs-logs/nginx/access.log
- type: log
  paths:
    - /data/fs-logs/mysql/slow-query.log
  close_rename: true
  close_remove: true
  close_inactive: 10m
  scan_frequency: 1m
  backoff: 1s
  max_backoff: 10s
  backoff_factor: 2
  harvester_limit: 10
  multiline.pattern: '^(# Time)'
  multiline.negate: true
  multiline.match: after
  multiline.timeout: 5s

output.kafka:
  hosts: ["kafka:9092"]

  topic: 'fs-logs'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
